-- ============================================================
-- ARKA Supabase Schema
-- Run this in your Supabase project → SQL Editor
-- ============================================================

-- profiles table (linked to auth.users)
CREATE TABLE IF NOT EXISTS public.profiles (
  id                  UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name           TEXT NOT NULL,
  email               TEXT NOT NULL,
  phone               TEXT,
  city                TEXT,
  delivery_zone           TEXT,
  platform                TEXT CHECK (platform IN ('zepto','blinkit','swiggy','zomato','dunzo','other')),
  avg_weekly_income       NUMERIC(10,2),
  avg_weekly_hours        NUMERIC(5,1),
  avg_weekly_deliveries   INTEGER,
  upi_id                  TEXT,
  onboarding_complete BOOLEAN DEFAULT FALSE,
  policy_status       TEXT DEFAULT 'pending' CHECK (policy_status IN ('pending','active','inactive','rejected')),
  -- Policy enrollment fields
  plan_type           TEXT CHECK (plan_type IN ('daily','weekly','monthly')),
  plan_start_date     TIMESTAMPTZ,
  plan_expires_at     TIMESTAMPTZ,
  plan_premium_inr    NUMERIC(8,2),
  risk_score          NUMERIC(5,2),
  premium_tier        NUMERIC(3,1),   -- 1.0, 2.0, or 3.0 (%)
  created_at          TIMESTAMPTZ DEFAULT NOW(),
  updated_at          TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Policy: users can only read/write their own profile
CREATE POLICY "Users can view own profile"
  ON public.profiles FOR SELECT
  USING (auth.uid() = id);

CREATE POLICY "Users can insert own profile"
  ON public.profiles FOR INSERT
  WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update own profile"
  ON public.profiles FOR UPDATE
  USING (auth.uid() = id);

-- Auto-update updated_at
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_updated_at
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

-- ============================================================
-- trigger_data table — stores live API snapshots per zone
-- Populated every 10 min by the backend APScheduler job
-- ============================================================

CREATE TABLE public.trigger_data (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zone_id             TEXT NOT NULL,
    temperature_c       DOUBLE PRECISION,
    feels_like_c        DOUBLE PRECISION,
    heat_index_c        DOUBLE PRECISION,
    wind_speed          DOUBLE PRECISION,
    rainfall_mm         DOUBLE PRECISION,
    humidity_pct        DOUBLE PRECISION,
    visibility          DOUBLE PRECISION,
    aqi_index           INTEGER,
    currentSpeed        INTEGER,
    freeFlowSpeed       INTEGER,
    currentTravelTime   INTEGER,
    freeFlowTravelTime  INTEGER,
    roadClosure         BOOLEAN,
    timestamp           TIMESTAMPTZ NOT NULL,
    created_at          TIMESTAMPTZ DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);

-- Enable Row Level Security
ALTER TABLE public.trigger_data ENABLE ROW LEVEL SECURITY;

-- Policy: backend service role can insert (uses service-role key, bypasses RLS)
-- Authenticated users can read the data (e.g. for dashboards)
CREATE POLICY "Allow authenticated users to read trigger data"
  ON public.trigger_data FOR SELECT
  TO authenticated
  USING (TRUE);

-- Index on zone_id + timestamp for fast range queries
CREATE INDEX idx_trigger_data_zone_time
  ON public.trigger_data (zone_id, timestamp DESC);

